
    export const REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
    export const REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
    export const REGISTER_FAILURE ='USER_REGISTER_FAILURE';

    export const LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
    export const LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
    export const LOGIN_FAILURE = 'USER_LOGIN_FAILURE';

    export const LOGOUT= 'USER_LOGOUT';

    export const DELETE_REQUEST= 'USERS_DELETE REQUEST';
    export const DELETE_SUCCESS= 'USERS_DELETE_SUCCESS';
    export const DELETE_FAILURE= 'USERS_DELETE_FAILURE';
    
    export const GETALL_REQUEST= 'USERS_GETALL_REQUEST';
    export const GETALL_SUCCESS= 'USERS_GETALL_SUCCESS';
    export const GETALL_FAILURE= 'USERS_GETALL_FAILURE';